import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Layout from '@/components/Layout'
import profilepic from '../../public/images/profile/web-developer--324527604.png'
import Animatedtext from '@/components/Animatedtext'
import Link from 'next/link'
import { LinkArrow } from '@/components/Icons'
import HireMe from '@/components/HireMe'
import lightbulb from '../../public/images/svgs/miscellaneous_icons_1.svg'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        
      </Head>
      <main className='flex items-center w-full text-dark min-h-screen'>
        <Layout className='pt-0'>
          <div className='flex items-center justify-between w-full'>
            <div className='w-1/2'>
            <Image src={profilepic} alt='Talib' className='w-[90%] h-auto rounded-full'/>
            </div>
            <div className='w-1/2 flex flex-col item-center self-center'>
              
              <Animatedtext text='Turning Vision Into Reality With Code And Design.' className='!text-6xl  !text-left' />
              <p className='my-4 text-base font-medium'>As a skilled full-stack developer, I am dedicated to turning ideas into innovative web applications. 
               Explore my latest projects and articles, showcasing my expertise in React.js and web development.</p>    
               <div className='flex items-center self-start mt-2'> 
                   <Link href="dummy.pdf" target='_blank' 
                   className='flex items-center bg-dark text-light
                   rounded-lg text-lg font-semibold p-3 px-6 hover:bg-light hover:text-dark border border-solid border-transparent border-2 hover:border-dark '
                   download={true}  
                   >Resume <LinkArrow className='w-6 ml-1'/></Link>
                   <Link href="mailto:mohammedtalib5@gmail.com" target='_blank' 
                   className='ml-4 text-lg font-medium capitalize text-dark underline'
                   >Contact</Link>
               </div>
            </div>
          </div>
        </Layout>
        <HireMe/>
        <div className='absolute w-24 right-8 inline-block bottom-8'>
          <Image className='w-full h-auto' src={lightbulb} alt='themeswitcher'></Image>
        </div>
      </main>
    </>
  )
}